# 🔴 2026-07-02 CODE_TO_MODEL 桶表全仓对账 · scanner-nn-upgrade teammate
"""code_to_model_table.py — scanner issue code → 数据飞轮训练桶查表（唯一真理源）。

从 data_collector.py 拆出（该文件加上本表会超 1000 行 · 用户全局规则要求单文件拆分）。
data_collector.py 只 import 这里的 CODE_TO_MODEL / CODE_PREFIX_TO_MODEL /
EXCLUDED_FROM_FLYWHEEL / resolve_model_for_code，不直接维护映射数据。

背景：core/scripts/ 209 个 scanner/aggregate 各自 emit 静态 issue code，本表把每个
code 映射到 13 个模型训练桶（ai_tone/hook_strength/surprisal/tension_trajectory/
coherence/emotion_arc/style_fidelity/dialogue_pragmatics/promise_payoff/voice_drift/
character_trajectory/action_mentalizing/cognitive_load）之一，或复用 data_collector.py
里已有的非-13-桶池名（judge_reliability/waiver_calibration/scanner_reliability/
reader_experience——这几个池子已被 _collect_judge_reports 等函数使用，语义比硬塞进
13 桶更准），或显式收进 EXCLUDED_FROM_FLYWHEEL（ledger/契约/infra 信号·非正文judge）。

_collect_weak_labels / _collect_strong_labels（data_collector.py）遇到
CODE_TO_MODEL.get(code) 为 None 就静默 continue —— 未注册 code 的训练信号被丢弃。
2026-07-02 全仓 AST 静态扫描（tests/test_code_to_model_coverage.py 同款提取逻辑）核出
468 个静态 code 从未注册，逐一归桶/豁免补齐（见下）。回归锁：新 scanner 忘记注册会被
test_code_to_model_coverage.py 直接测红。
"""
from __future__ import annotations

CODE_TO_MODEL: dict[str, str] = {
    # AI 腔 / 模板化 / 语言塑料感
    "BANNED_WORD": "ai_tone",
    "SEMANTIC_METAPHOR_EXPLAIN": "ai_tone",
    "SEMANTIC_APHORISM": "ai_tone",
    "SEMANTIC_NEG_PARALLEL": "ai_tone",
    "SEMANTIC_COPULA_AVOID": "ai_tone",
    "SEMANTIC_FAKE_RANGE": "ai_tone",
    "SEMANTIC_OVER_HEDGE": "ai_tone",
    "SEMANTIC_FORCED_TRIPLE": "ai_tone",
    "SEMANTIC_TAG_SYNONYM_CYCLE": "ai_tone",
    "SYNTACTIC_NGRAM_REPETITION": "ai_tone",
    "RHETORIC_REPETITION": "ai_tone",
    "REPEAT_NOUN_DENSITY": "ai_tone",
    "SUBTEXT_ON_THE_NOSE": "ai_tone",
    "TRANSLATIONESE_RESIDUAL": "ai_tone",
    # LLM_GRAMMAR_OVERUSE（旧注册·从未被任何 scanner 实际 emit 过，naming drift 死码）
    # 已删除，真实 code 见下方新增区 LLM_GRAMMAR_PARTICIPIAL_OVERUSE 等 4 个具体变体
    # （llm_grammar_overuse_scanner.py 的 ISSUE_CODES 元组·scanner_registry.json 已核实）。

    # 钩子 / 信息密度 / 张力轨迹
    "HOOK_WEAK": "hook_strength",
    "CHAPTER_END_FORBIDDEN_SCREENPLAY": "hook_strength",
    "CHAPTER_END_FORBIDDEN_TRANSITION": "hook_strength",
    "SURPRISAL_TOO_FLAT": "surprisal",
    "SURPRISAL_CLIFF": "surprisal",
    "SURPRISAL_MONOTONE": "surprisal",
    "INFO_DENSITY_IMBALANCE": "surprisal",
    "SCH_HIERARCHY_INVERTED": "surprisal",  # 2026-07-01 补全：cross_cluster_hierarchical_position_surprisal_aggregate
    "RHYTHM_FLATLINE": "tension_trajectory",
    "NARRATIVE_RHYTHM_MONOTONE": "tension_trajectory",
    "PREMATURE_RESOLUTION": "tension_trajectory",
    "WC_TOO_SHORT": "tension_trajectory",
    # 2026-07-01 补全：爆点前张力铺垫同族（forecasting_tension/frisson_lead_window/gaoneng_anticipation_signposting）
    "FORECASTING_TENSION_FLAT": "tension_trajectory",
    "FRISSON_LEAD_FLAT": "tension_trajectory",
    "FRISSON_CLIMAX_OVERLOAD": "tension_trajectory",
    "FRISSON_NO_CLIMAX_FOUND": "tension_trajectory",
    "BURST_LEAD_SIGNPOST_LOW": "tension_trajectory",
    "BURST_LEAD_SIGNPOST_HIGH": "tension_trajectory",
    "BURST_LEAD_NO_PEAK_FOUND": "tension_trajectory",

    # 连贯 / situation model / 读者心智桥接
    "COHERENCE_BREAK": "coherence",
    "COHERENCE_LOW_OVERALL": "coherence",
    "COHERENCE_UNSTABLE": "coherence",
    "SITUATION_MODEL_DIM_DROPOUT": "coherence",
    "CENTERING_ROUGH_SHIFT_OVERLOAD": "coherence",
    "PARATACTIC_LOGIC_GAP": "coherence",
    "EPISODE_BRIDGE_WEAK": "coherence",
    "SCENE_GROUNDING_THIN": "coherence",
    "TEMPORAL_GROUNDING_THIN": "coherence",
    # 2026-07-07 ConStory 盲区三件套：时序倒错/空间瞬移/描述类 NLI 矛盾（语义连贯信号·全 advisory）
    "DRAFT_TEMPORAL_ORDER_REVERSED": "coherence",
    "SPATIAL_CONTINUITY_TELEPORT": "coherence",
    "LOCKED_FACT_DESCRIPTIVE_CONTRADICTION": "coherence",
    "FUTURE_KNOWLEDGE_LEAK": "coherence",
    "POV_HEAD_HOPPING": "coherence",
    "POV_VIOLATION": "coherence",

    # 情绪弧 / VAD / 情感签名
    "EMOTION_ARC_FLAT": "emotion_arc",
    "EMOTION_ARC_MISMATCH": "emotion_arc",
    "EMOTION_CURVE_RESCAN_DRIFT": "emotion_arc",
    "CONGENIALITY_SKEW": "emotion_arc",
    "RASA_LAYER_DOMINANT_DRIFT": "emotion_arc",
    "RASA_CAUSAL_BREAK_MISMATCH": "emotion_arc",
    # 2026-07-01 补全：cn_emotion_vad_drift / cross_cluster_ousiometric_emd 此前未接入任何桶
    "CN_EMOTION_ANGLO_DRIFT": "emotion_arc",
    "CN_EMOTION_CULTURAL_UNDERUSE": "emotion_arc",
    "CN_EMOTION_BINARY_POLARIZATION": "emotion_arc",
    "CN_EMOTION_NO_EMOTION_WORDS": "emotion_arc",
    "OUSIOMETRIC_OSCILLATION_DEGRADED": "emotion_arc",

    # 风格保真 / 转场 / 韵律
    "STYLE_SIMILARITY_LOW": "style_fidelity",
    "SEAM_DISTRIBUTION_DRIFT": "style_fidelity",
    "PROSE_RHYTHM_DRIFT": "style_fidelity",
    "INTRA_CLUSTER_STYLE_BREAK": "style_fidelity",
    "FUNCTION_WORD_FINGERPRINT_DRIFT": "style_fidelity",
    "ANACHRONY_ORDER_THIN": "style_fidelity",
    "NARRATIVE_FREQUENCY_FLAT": "style_fidelity",
    # ANADIPLOSIS_OVERUSE / ANADIPLOSIS_UNDERUSE（旧注册·naming drift 死码，从未被
    # anadiplosis_scanner.py 实际 emit 过）已删除，真实 code 见下方新增区
    # ANADIPLOSIS_DETECTED / ANADIPLOSIS_OVER_BASELINE / ANADIPLOSIS_UNDER_BASELINE。

    # 对白语用 / 群戏调度
    "DIALOGUE_NATURALNESS_LOW": "dialogue_pragmatics",
    "LONG_MONOLOGUE": "dialogue_pragmatics",
    "TONE_INCONSISTENCY": "dialogue_pragmatics",
    "GROUP_DIALOGUE_NAME_CRUTCH": "dialogue_pragmatics",
    "GROUP_DIALOGUE_IMBALANCE": "dialogue_pragmatics",
    "DISPREFERRED_TURN_BARE": "dialogue_pragmatics",
    # ATTRIBUTION_MODE_DRIFT（旧注册·naming drift 死码，从未被 attribution_mode_scanner.py
    # 实际 emit 过）已删除，真实 code 见下方新增区 ATTRIBUTION_MODE_MONOTONE 等 3 个。
    "QUOTATIVE_SIGNATURE_DRIFT": "dialogue_pragmatics",

    # 伏笔 / 揭示公平性 / promise-payoff
    "REVEAL_TELL_OVERUSE": "promise_payoff",
    "FORESHADOWING_NOT_PLANTED": "promise_payoff",
    "FORESHADOWING_NOT_REINFORCED": "promise_payoff",
    "FORESHADOWING_HANDOFF_WEAK": "promise_payoff",
    "FORESHADOWING_PAYOFF_TARGET_NOT_OPEN": "promise_payoff",  # 2026-07-06 P1 伏笔三态生命周期：payoff 指向非 open 条目
    "REVEAL_FAIRNESS_LOW": "promise_payoff",
    "RED_HERRING_RECALL_WEAK": "promise_payoff",
    "MACGUFFIN_ENTANGLEMENT_LOW": "promise_payoff",

    # 角色轨迹 / actant / voice / power progression
    "VOICE_DRIFT": "voice_drift",
    "VOICE_DRIFT_CROSS_SCENE": "voice_drift",
    "CATCHPHRASE_OVERUSE": "voice_drift",
    "PERSONA_DRIFT": "character_trajectory",
    "ACTANT_DRIFT": "character_trajectory",
    "ACTANT_DRIFT_NO_PIVOT": "character_trajectory",
    "ACTANT_VACANCY": "character_trajectory",
    "ACTANT_OVERLOADED": "character_trajectory",
    "ANTAGONIST_VALENCE_DRIFT_UNAUTHORIZED": "character_trajectory",
    "ANTAGONIST_ROTATION_STALE": "character_trajectory",
    "POWER_PROGRESSION_JUMP": "character_trajectory",

    # 动作/内省比例与读者负荷
    "ACTION_MENTAL_RATIO_DRIFT": "action_mentalizing",
    "ACTION_PURE_PHYSICAL": "action_mentalizing",
    "ACTION_PURE_MENTAL": "action_mentalizing",
    "COGNITIVE_OVERLOAD": "cognitive_load",
    "CAST_ECONOMY_OVERLOAD": "cognitive_load",
    # 2026-07-01 补全：expert_blindspot_scanner 此前未接入任何桶
    "EXPERT_BLINDSPOT_DRIFT": "cognitive_load",
    "EXPERT_BLINDSPOT_DRIFT_COMPLEX": "cognitive_load",

    # ============ 2026-07-02 全仓对账新增（468 静态 code 全集 - 53 EXCLUDED = 415） ============
    # ---- ai_tone（AI 腔/模板化/塑料感） ----
    "CAUSAL_HEURISTIC_LEAK": "ai_tone",
    "CLICHE_AI_WORDS_CN": "ai_tone",
    "DIALOGUE_TAG_MECHANIZATION": "ai_tone",
    "LLM_GRAMMAR_NESTED_X_DE_Y_OVERUSE": "ai_tone",
    "LLM_GRAMMAR_NOMINALIZATION_OVERUSE": "ai_tone",
    "LLM_GRAMMAR_PARALLEL_AND_STACK_OVERUSE": "ai_tone",
    "LLM_GRAMMAR_PARTICIPIAL_OVERUSE": "ai_tone",
    "METAPHOR_OVERUSE": "ai_tone",
    "MODIFIER_STACK": "ai_tone",
    "NEGATION_DESC_OVERUSE": "ai_tone",
    "ON_THE_NOSE_EMOTION_DENSITY": "ai_tone",
    "PARAGRAPH_SUBJECT_HIGH_ABS": "ai_tone",
    "PARAGRAPH_SUBJECT_REPETITION": "ai_tone",
    "PARA_FIRST_WORD_CONCENTRATION": "ai_tone",
    "PUNCTUATION_HALFWIDTH_LEAK": "ai_tone",
    "SENTENCE_PARTICLE_MONO": "ai_tone",
    "SUBJECT_ACTION_HIGH": "ai_tone",
    "SUBJECT_ACTION_MECHANICAL": "ai_tone",
    "TELL_OVERUSE": "ai_tone",
    "TELL_RATE_HIGH": "ai_tone",
    # ---- hook_strength（钩子/章末锚定） ----
    "BRIDGE_NEW_HOOK_TOO_EARLY": "hook_strength",
    "BRIDGE_PAYWALL_HOOK_GRADIENT_OFF": "hook_strength",
    "BRIDGE_RESOLVE_TOO_LATE": "hook_strength",
    "CHAPTER_END_CLOSURE_ADVISORY": "hook_strength",
    "CHAPTER_END_NO_ANCHOR": "hook_strength",
    "CHAPTER_END_WEAK_ANCHOR": "hook_strength",
    "CLIFFHANGER_NOT_RESONATED": "hook_strength",
    "CLIFFHANGER_QUOTA_OVER": "hook_strength",
    "ENDING_TYPE_LOW_DIVERSITY": "hook_strength",
    "ENDING_TYPE_MISSING": "hook_strength",
    "ENDING_TYPE_MONOTONE": "hook_strength",
    "ENDING_TYPE_RUN": "hook_strength",
    "GOLDEN_DEGRADATION": "hook_strength",
    "GOLDEN_FLAT": "hook_strength",
    "HOOK_PERSISTENT_LOW": "hook_strength",
    "HOOK_STRENGTH_DECLINE": "hook_strength",
    "HOOK_SUMMARY_ENDING": "hook_strength",
    "LAZY_SPAWN_NEVER_PROMOTED": "hook_strength",
    "OPENING_WARMUP": "hook_strength",
    "OPENING_WINDOW_MILESTONE_THIN": "hook_strength",
    "OTTER_TAIL_DETECTED": "hook_strength",
    "OTTER_TAIL_INCOMPATIBLE": "hook_strength",
    "OTTER_TAIL_MISSING": "hook_strength",
    "READER_EXP_GOLDEN_THREE": "hook_strength",
    "READER_EXP_HOOK_STRENGTH": "hook_strength",
    "VOLUME_TRANSITION_EMPTY_OPEN": "hook_strength",
    "VOLUME_TRANSITION_HARD_RESET": "hook_strength",
    "VOLUME_TRANSITION_HOOK_MISS": "hook_strength",
    # ---- surprisal（信息密度/惊异度） ----
    "AUTHOR_BRAND_PERPLEXITY_BAND_MISSING": "surprisal",
    "AUTHOR_BRAND_PERPLEXITY_DRIFT_HIGH": "surprisal",
    "AUTHOR_BRAND_PERPLEXITY_DRIFT_LOW": "surprisal",
    "BELIEF_INTENT_MISSING": "surprisal",
    "BELIEF_PRESERVE_RED_HERRING_KILLED": "surprisal",
    "BELIEF_UPDATE_NO_SURPRISE": "surprisal",
    "PROSODIC_PAUSE_VALLEY_MISSING": "surprisal",
    "WORLD_TERM_INFO_DUMP": "surprisal",
    # ---- tension_trajectory（节奏/张力/爆点） ----
    "ALL_WIN_NO_SETBACK": "tension_trajectory",
    "BEAT_GAP_TOO_LONG": "tension_trajectory",
    "BEAT_MISSED": "tension_trajectory",
    "BREMOND_CADENCE_MONOTONE": "tension_trajectory",
    "BREMOND_CADENCE_OVER_FAILURE": "tension_trajectory",
    "BREMOND_CADENCE_OVER_SUCCESS": "tension_trajectory",
    "BURST_TYPE_MISMATCH": "tension_trajectory",
    "BURST_TYPE_NOT_DELIVERED": "tension_trajectory",
    "BURST_TYPE_NO_INTENT": "tension_trajectory",
    "BURST_TYPE_TAIL_FLAT": "tension_trajectory",
    "DEUS_EX_SOLUTION": "tension_trajectory",
    "DRAMATIC_IRONY_DRIFT": "tension_trajectory",
    "DRAMATIC_IRONY_GAP_EMPTY": "tension_trajectory",
    "DRAMATIC_IRONY_GAP_STALE": "tension_trajectory",
    "DRAMATIC_QUESTION_STALE": "tension_trajectory",
    "DWELL_RATIO_LOW": "tension_trajectory",
    "EVENT_BOUNDARY_DEFAULT": "tension_trajectory",
    "EVENT_BOUNDARY_TOO_DULL": "tension_trajectory",
    "EVENT_BOUNDARY_TOO_SHARP": "tension_trajectory",
    "EVENT_DENSITY_RHYTHM_OVER": "tension_trajectory",
    "FAILURE_SEGMENT_DENSITY_GAP": "tension_trajectory",
    "GLASER_LEVER_MISSING": "tension_trajectory",
    "GLASER_LEVER_OK": "tension_trajectory",
    "GLASER_LEVER_THIN": "tension_trajectory",
    "HORIZONTAL_CLOUD_PRESENT": "tension_trajectory",
    "HORIZONTAL_CLOUD_RECOMMEND": "tension_trajectory",
    "LENGTH_OUTLIER": "tension_trajectory",
    "LENGTH_TREND_DROP": "tension_trajectory",
    "LENGTH_VARIANCE_HIGH": "tension_trajectory",
    "MICRODRAMA_HEAD_3S_NO_ACTION": "tension_trajectory",
    "MICRODRAMA_MID_15S_NO_TWIST": "tension_trajectory",
    "MICRODRAMA_NOT_SHORTDRAMA_SKIP": "tension_trajectory",
    "MICRODRAMA_TAIL_30S_NO_HOOK": "tension_trajectory",
    "MID_CHAPTER_CLIFF_CADENCE_OFF_BAND": "tension_trajectory",
    "NO_OPEN_DRAMATIC_QUESTION": "tension_trajectory",
    "OPEN_CLOSE_IMBALANCE": "tension_trajectory",
    "OS_DOMINANT": "tension_trajectory",
    "PACE_CARRIER_PURE_RHYTHM_HOOK": "tension_trajectory",
    "PACE_CARRIER_WINDOW_EMPTY": "tension_trajectory",
    "PACE_CARRIER_WINDOW_OVER_LOADED": "tension_trajectory",
    "PER_CLUSTER_COVERAGE_LOW": "tension_trajectory",
    "PLOT_ARMOR_INFLATION": "tension_trajectory",
    "PROGRESSION_TOO_DENSE": "tension_trajectory",
    "SAGGING_MIDDLE_NEEDS_MIDPOINT_BOMB": "tension_trajectory",
    "SAGGING_MIDDLE_PURPOSE_VOID": "tension_trajectory",
    "SAGGING_MIDDLE_REVERSAL_VOID": "tension_trajectory",
    "SAGGING_MIDDLE_STAKES_FLAT": "tension_trajectory",
    "SCENE_GAP_ABSENT": "tension_trajectory",
    "SCENE_GAP_MONOTONE": "tension_trajectory",
    "SEQUEL_DROUGHT": "tension_trajectory",
    "SINGLE_GAP_TYPE_MONOTONE": "tension_trajectory",
    "THROUGHLINE_DORMANT": "tension_trajectory",
    "THROUGHLINE_MARGINALIZED": "tension_trajectory",
    "TRY_FAIL_NOT_REFLECTED": "tension_trajectory",
    "TURN_FIDELITY_LOW": "tension_trajectory",
    "UNIT_TYPE_MISSING": "tension_trajectory",
    "VALUE_NO_TURN": "tension_trajectory",
    "VOLUME_ARC_DRIFT": "tension_trajectory",
    "WC_TOO_LONG": "tension_trajectory",
    # ---- coherence（连贯/situation model/时空因果/POV） ----
    "ACW_DRIFT_FROM_CENTER": "coherence",
    "ANACHRONISM_DETECTED": "coherence",
    "CHARACTER_KNOWLEDGE_LEAK": "coherence",
    "CHARACTER_KTH_ORDER_BELIEF_DRIFT": "coherence",
    "CHRONOTOPE_LOW_DIVERSITY": "coherence",
    "CHRONOTOPE_MONOTONY": "coherence",
    "CONSISTENCY_HOTSPOT_COOCCURRENCE": "coherence",
    "CROSS_BOOK_INVARIANT_BREACH": "coherence",
    "EDGE_CYCLE": "coherence",
    # 2026-07-07 A10 实体状态时间线图矛盾（Magnet/Atlas·cross_cluster_entity_state_graph_aggregate）
    "ENTITY_STATE_GRAPH_CONFLICT": "coherence",
    "FIRSTPERSON_RETRO_HINDSIGHT_THIN": "coherence",
    "FOCALIZER_PERCEPTION_OUT_OF_BOUNDS": "coherence",
    "FRAME_TALE_DRIFT": "coherence",
    "INTEGRATION_RIDGE_ABSENT": "coherence",
    "INTEGRATION_RIDGE_TOO_EARLY": "coherence",
    "NODE_ORPHAN": "coherence",
    "OBJECT_CONTINUITY_BROKEN": "coherence",
    "PARATAXIS_OFF_AUTHOR_BAND": "coherence",
    "POV_LOCKED": "coherence",
    "POV_NON_PROTAGONIST_SCENE": "coherence",
    "POV_OVERCONCENTRATED": "coherence",
    "PROSE_AXIS_FLIP": "coherence",
    "PROSE_AXIS_OK": "coherence",
    "PROSE_AXIS_TRIPLE_EMPTY": "coherence",
    "RULE_TEXT_AMBIGUITY_LOW": "coherence",
    # [2026-07-06 P1移植 scene_receipts] 文本-storyboard 对齐是连贯性信号
    "SCENE_RECEIPT_COVERAGE_GAP": "coherence",
    "TEMPORAL_BOOTSTRAP_LOOP": "coherence",
    "TIME_ANCHOR_DROP": "coherence",
    "TIME_JUMP_UNEXPLAINED": "coherence",
    "TOPIC_DRIFT_DETECTED": "coherence",
    "TOPIC_DRIFT_SUSTAINED": "coherence",
    "TOPIC_RETURN_ABRUPT": "coherence",
    "UNRELIABLE_NARRATOR_SIGNAL_THIN": "coherence",
    "WEAK_CAUSAL_LINK": "coherence",
    "WRITER_INTENT_AGENDA_DRIFT": "coherence",
    "WRITER_INTENT_NO_ANCHOR": "coherence",
    "WRITER_INTENT_OK": "coherence",
    # ---- emotion_arc（情绪弧/VAD/情感签名） ----
    "BIBLIOTHERAPY_ARC_TRIAD_MISSING": "emotion_arc",
    "CHILLS_ARCH_INCOMPLETE": "emotion_arc",
    "CN_EMOTION_OK": "emotion_arc",
    "DIALOGUE_CONTAGION_ABNORMAL": "emotion_arc",
    "EMOTIONAL_PUNCT_SPARSE": "emotion_arc",
    "EMOTION_DISCONTINUITY": "emotion_arc",
    "EMOTION_FLATLINE": "emotion_arc",
    "EMOTION_GRANULARITY_COARSE": "emotion_arc",
    "EMOTION_RUN_TOO_LONG": "emotion_arc",
    "EMPATHIC_CONCERN_DISTRESS_IMBALANCE": "emotion_arc",
    "NARR_DIAL_VAD_OVERCOUPLED": "emotion_arc",
    "PHYSIO_CUE_FACIAL_BIAS": "emotion_arc",
    "RASA_CAUSAL_BREAK_NO_ANUBHAVA": "emotion_arc",
    "RASA_CAUSAL_BREAK_NO_VIBHAVA": "emotion_arc",
    "RASA_CAUSAL_OK": "emotion_arc",
    "RASA_LAYER_OK": "emotion_arc",
    "RASA_LAYER_TRANSIENT_FLAT": "emotion_arc",
    "VAD_UED_DRIFT": "emotion_arc",
    # ---- style_fidelity（风格保真/转场/韵律/修辞装置） ----
    "ANADIPLOSIS_DETECTED": "style_fidelity",
    "ANADIPLOSIS_OVER_BASELINE": "style_fidelity",
    "ANADIPLOSIS_UNDER_BASELINE": "style_fidelity",
    "ASPECT_GROUNDING_OVERUSE": "style_fidelity",
    "ASPECT_GROUNDING_THIN": "style_fidelity",
    "AUDIO_PERF_ABSTRACT_NOUN_PILE": "style_fidelity",
    "AUDIO_PERF_PARENTHESIS_DRAG": "style_fidelity",
    "AUDIO_PERF_TRI_CLAUSE_HEAVY": "style_fidelity",
    "AUTHOR_SIGNATURE_MISMATCH": "style_fidelity",
    "AUTHOR_SIGNATURE_NOT_PLACED": "style_fidelity",
    "AUTHOR_SIGNATURE_OK": "style_fidelity",
    "AV_TRAIT_DRIFT": "style_fidelity",
    "AXIS_ALL_HIGH_PASS": "style_fidelity",
    "BIBER_MDA_DRIFT": "style_fidelity",
    "CHENGYU_MISUSE_SUSPECTED": "style_fidelity",
    "CLASH_UNRESOLVED": "style_fidelity",
    "COHN_MODE_DRIFT": "style_fidelity",
    "DISCORDANCE_SIGNAL_THIN": "style_fidelity",
    "DISTANCE_FLATTENED": "style_fidelity",
    "DISTANCE_TENSE_DRIFT": "style_fidelity",
    "DRIFT_FROM_AUTHOR": "style_fidelity",
    "DURATION_MIX_DRIFT": "style_fidelity",
    "EXCESS_VOCAB_SIGNATURE_HIT": "style_fidelity",
    "EXPANSION_RATIO_DRIFT": "style_fidelity",
    "FIRST_ENCOUNTER_LABEL_FIRST": "style_fidelity",
    "FOREGROUNDING_TRIAD_DENSITY_OFF_BAND": "style_fidelity",
    "GENRE_BLEND_FLAT": "style_fidelity",
    "GENRE_DOMINANCE_INVERSION": "style_fidelity",
    "GENRE_PRIMARY_STARVED": "style_fidelity",
    "HOMOPHONIC_PUN_THIN": "style_fidelity",
    "IDIOM_COOLDOWN_VIOLATION": "style_fidelity",
    "IMAGEABILITY_OFF_BAND": "style_fidelity",
    "IMAGEABILITY_ROUND_TRIP_HIGH": "style_fidelity",
    "IMAGEABILITY_ROUND_TRIP_LOW": "style_fidelity",
    "IMAGEABILITY_ROUND_TRIP_NA": "style_fidelity",
    "INTENTIONAL_RECURRENCE_DETECTED": "style_fidelity",
    "INTENTIONAL_RECURRENCE_REAL_REPEAT": "style_fidelity",
    "INTENTIONAL_RECURRENCE_THIN_DATA": "style_fidelity",
    "L3A_LOW_BURSTINESS": "style_fidelity",
    "L3A_STYLE_ONLY_LOW": "style_fidelity",
    "L3A_WINDOW_COLLAPSE": "style_fidelity",
    "LISH_CONSECUTION_THIN": "style_fidelity",
    "LISH_PHONIC_THIN": "style_fidelity",
    "LISH_TEMPLATE_REPEAT": "style_fidelity",
    "LITRPG_STRUCTURE": "style_fidelity",
    "LOAD_BEARING_ALLUSION_NO_GLOSS": "style_fidelity",
    "LOCATION_NEVER_VISITED": "style_fidelity",
    "LOCATION_OVERFREQ": "style_fidelity",
    "LOCATION_RHYTHM_BROKEN": "style_fidelity",
    "LOCATION_SIGNATURE_DRIFT": "style_fidelity",
    "LONGRANGE_STYLE_DRIFT": "style_fidelity",
    "METALEPSIS_BUDGET_DRIFT": "style_fidelity",
    "MIMETIC_DENSITY_DRIFT": "style_fidelity",
    "MOTIF_DORMANT": "style_fidelity",
    "MOTIF_OVER_SATURATED": "style_fidelity",
    "MOTIF_PAYOFF_DUE": "style_fidelity",
    "MOTIF_SEED_PROLIFERATION": "style_fidelity",
    "NARRATEE_DRIFT": "style_fidelity",
    "NARRATOR_COMMENTARY_OVERUSE": "style_fidelity",
    "OBJECT_BIOGRAPHY_THIN": "style_fidelity",
    "OVER_BRIGHT": "style_fidelity",
    "OVER_DARK": "style_fidelity",
    "PARAGRAPH_300CJK_PAYLOAD_OFF_BAND": "style_fidelity",
    "PARAGRAPH_LENGTH_DEGRADATION": "style_fidelity",
    "PARATEXT_INTERPOLATION_THIN": "style_fidelity",
    "PARATEXT_TYPE_MONOTONE": "style_fidelity",
    "PREMISE_BLEND_CARD_MISSING": "style_fidelity",
    "PREMISE_BLEND_EMERGENCE_MISSING": "style_fidelity",
    "PREMISE_BLEND_INPUT_DROP": "style_fidelity",
    "PREMISE_BLEND_LEXICAL_OVER": "style_fidelity",
    "REGISTER_DRIFT": "style_fidelity",
    "RESOURCE_LEDGER_THIN": "style_fidelity",
    "REVISION_REDUCED_AUTHOR_FIDELITY": "style_fidelity",
    "RHETORICAL_BALANCE_DRIFT": "style_fidelity",
    "RHETORICAL_CATEGORY_COLLAPSE": "style_fidelity",
    "RHETORICAL_INVENTORY_THIN": "style_fidelity",
    "RHETORIC_PARALLEL_GAP": "style_fidelity",
    "SCENE_OPENER_XING_THIN": "style_fidelity",
    "SECOND_ORDER_RHYTHM_FLAT": "style_fidelity",
    "SENSORY_IMBALANCE_VISUAL": "style_fidelity",
    "SFS_COMPENSATION_GAP": "style_fidelity",
    "SFS_DIMENSION_COLLAPSE": "style_fidelity",
    "SFS_PLOT_CONFOUND_RISK": "style_fidelity",
    "SFS_POORLY_CALIBRATED_FOR_AUTHOR": "style_fidelity",
    "SOUNDMARK_ABSENT": "style_fidelity",
    "SOUNDSCAPE_MONOTONE": "style_fidelity",
    "SOUNDSCAPE_THIN": "style_fidelity",
    "STATUS_BLOCK_DENSITY_DRIFT": "style_fidelity",
    "STATUS_BLOCK_UNAUTHORIZED_INTRODUCTION": "style_fidelity",
    "STYLE_BREAK_DETECTED": "style_fidelity",
    "STYLE_SIMILARITY_DRIFT": "style_fidelity",
    "SYNESTHESIA_OVERUSE": "style_fidelity",
    "THEMATIC_ARGUMENT_IMBALANCE": "style_fidelity",
    "TITLE_CONCRETENESS_DRIFT": "style_fidelity",
    "TONAL_PENDULUM_FLAT": "style_fidelity",
    "ZEUGMA_DETECTED": "style_fidelity",
    "ZEUGMA_OVER_BASELINE": "style_fidelity",
    "ZEUGMA_UNDER_BASELINE": "style_fidelity",
    "ZHANGHUI_HUIMU_PARALLELISM_BROKEN": "style_fidelity",
    "ZIPF_ALPHA_DRIFT": "style_fidelity",
    "ZP_DENSITY_OFF_AUTHOR_BAND": "style_fidelity",
    # ---- dialogue_pragmatics（对白语用/群戏调度） ----
    "ATTRIBUTION_DROUGHT_LONG": "dialogue_pragmatics",
    "ATTRIBUTION_MODE_MONOTONE": "dialogue_pragmatics",
    "AUTHOR_QUOTATIVE_PALETTE_COLLAPSE": "dialogue_pragmatics",
    "CHARACTER_QUOTATIVE_HOMOGENIZED": "dialogue_pragmatics",
    "COTTON_NEEDLE_BELOW_TARGET": "dialogue_pragmatics",
    "COTTON_NEEDLE_DETECTED": "dialogue_pragmatics",
    "COTTON_NEEDLE_OVER": "dialogue_pragmatics",
    "DIALOGUE_NO_BEATS": "dialogue_pragmatics",
    "DIALOGUE_SEQUENCE_EXPANSION_THIN": "dialogue_pragmatics",
    "DIALOGUE_STREAM_FLAT": "dialogue_pragmatics",
    "DIALOGUE_TAG_HIGH": "dialogue_pragmatics",
    "GRICEAN_FLOUTING_THIN": "dialogue_pragmatics",
    "MASS_REACTOR_DENSITY_DRIFT": "dialogue_pragmatics",
    "PARRHESIA_DENSITY_OK": "dialogue_pragmatics",
    "PARRHESIA_DENSITY_OVERFLOW": "dialogue_pragmatics",
    "PARRHESIA_DENSITY_THIN": "dialogue_pragmatics",
    "SILENCE_DENSITY_THIN": "dialogue_pragmatics",
    "THOUGHT_ATTRIBUTED_UNDISCLOSED": "dialogue_pragmatics",
    # ---- promise_payoff（伏笔/揭示公平性/悬念契约） ----
    "CHOICE_CONSEQUENCE_PENDING": "promise_payoff",
    "CHOICE_CONSEQUENCE_STARVING": "promise_payoff",
    "CHOICE_CONSEQUENCE_VISIBLE": "promise_payoff",
    "CHOICE_LEADS_TO_MISMATCH": "promise_payoff",
    "COVERT_FORESHADOWING_OPAQUE": "promise_payoff",
    "COVERT_FORESHADOWING_THIN": "promise_payoff",
    "DIRECTION_CARD_DILEMMA_THIN": "promise_payoff",
    "DIRECTION_CARD_FALSE_CHOICE_RISK": "promise_payoff",
    "DIRECTION_CARD_FRAMING_THIN": "promise_payoff",
    "DIRECTION_CARD_LOW_AGENCY": "promise_payoff",
    "DIRECTION_CARD_OK": "promise_payoff",
    "DIRECTION_CARD_OUTCOME_CONVERGENT": "promise_payoff",
    "FACTUAL_CLAIM_UNCORROBORATED": "promise_payoff",
    "FORESHADOWING_FIELDS_INCOMPLETE": "promise_payoff",
    "FORESHADOWING_NOT_PAID": "promise_payoff",
    "FORESHADOWING_PHYSICAL_EVIDENCE_MISSING": "promise_payoff",
    "FORESHADOW_NEVER_INITIATED": "promise_payoff",
    "FORESHADOW_NO_REINFORCEMENT": "promise_payoff",
    "FORESHADOW_OVERDUE": "promise_payoff",
    "FORESHADOW_OVER_REINFORCEMENT": "promise_payoff",
    "MACGUFFIN_ORNAMENTAL": "promise_payoff",
    "MYSTERY_COLD_OPEN": "promise_payoff",
    "MYSTERY_PLEDGE_DANGLING": "promise_payoff",
    "MYSTERY_PLEDGE_KEPT": "promise_payoff",
    "OFFSCREEN_ACTIONS_NOT_EXECUTED": "promise_payoff",
    "OFFSCREEN_BACKLOG": "promise_payoff",
    "OFFSCREEN_EVIDENCE_THIN": "promise_payoff",
    "OFFSCREEN_EXECUTION_LIE": "promise_payoff",
    "PAYOFF_UNREACHABLE": "promise_payoff",
    "PREMATURE_READER_REVEAL": "promise_payoff",
    "RED_HERRING_DANGLING": "promise_payoff",
    "SECRET_NOT_REVEALED": "promise_payoff",
    "USER_CHOICE_NOT_LANDED": "promise_payoff",
    "WILL_LEARN_NEVER_HINTED": "promise_payoff",
    "WILL_LEARN_OVERDUE": "promise_payoff",
    "XIEZI_HOMOLOGY_THIN": "promise_payoff",
    "XIEZI_KERNEL_NOT_RECALLED": "promise_payoff",
    # ---- voice_drift（voice 漂移/口头禅） ----
    "CATCHPHRASE_UNIFICATION": "voice_drift",
    "CATCHPHRASE_UNUSED": "voice_drift",
    "CHILD_VOICE_REGISTER_DRIFT": "voice_drift",
    "CROSS_CHARACTER_VOICE_COLLISION": "voice_drift",
    "INTER_CHARACTER_VOICE_COLLAPSE": "voice_drift",
    "VOICE_COLLAPSE_CROSS_CHAR": "voice_drift",
    # ---- character_trajectory（角色轨迹/actant/权力进阶/反派） ----
    "ACR_FRUSTRATION_MISMATCH": "character_trajectory",
    "AMBIGUOUS_FLAT_TRAJECTORY": "character_trajectory",
    "ANTAGONIST_FIDELITY_FLAT": "character_trajectory",
    "ANTAGONIST_ROTATION_MOTIVE_MONOTONE": "character_trajectory",
    "ANTAGONIST_ROTATION_POWER_MONOTONE": "character_trajectory",
    "ANTAGONIST_ROTATION_TIER_DOWNGRADE": "character_trajectory",
    "ANTAGONIST_ROTATION_VOID": "character_trajectory",
    "BEAT_STAGE_DIVERGENCE": "character_trajectory",
    "CAPABILITY_EMERGENCE_UNGROUNDED": "character_trajectory",
    "CHARACTER_COREF_AMBIGUOUS": "character_trajectory",
    "CHARACTER_MISSING": "character_trajectory",
    "CHARACTER_ORPHAN_DIALOGUE": "character_trajectory",
    "CHARACTER_ROTATION_BREAK": "character_trajectory",
    "CHARACTER_IDENTITY_ANCHOR_DRIFT": "character_trajectory",
    "CHARACTER_STATE_DRIFT_DETECTED": "character_trajectory",
    "CHARACTER_SUDDEN_APPEAR": "character_trajectory",
    "CHARACTER_THROUGH_LINE_BROKEN": "character_trajectory",
    "CHARACTER_VANISH": "character_trajectory",
    "CHARACTER_VOICELESS": "character_trajectory",
    "COPING_NEVER_TRIGGERED": "character_trajectory",
    "CROSS_BOOK_RANK_INFLATION": "character_trajectory",
    "ESCALATION_ACCELERATION_SPIKE": "character_trajectory",
    "INDIRECT_CHARACTERIZATION_THIN": "character_trajectory",
    "MENTAL_BREAK_FORGOTTEN": "character_trajectory",
    "MOVES_UNDERUSED": "character_trajectory",
    "MOVE_OVERUSE": "character_trajectory",
    "PERSONA_DRIFT_CURVE_TREND": "character_trajectory",
    "PERSONA_DRIFT_DETECTED": "character_trajectory",
    "POWER_TIER_REGRESSION": "character_trajectory",
    "PROGRESSION_STALL": "character_trajectory",
    "PROTAGONIST_NAME_OVERFLOW": "character_trajectory",
    "PROTAGONIST_WEAK": "character_trajectory",
    "RELATIONSHIP_FROZEN": "character_trajectory",
    "RELATIONSHIP_OUT_OF_BOUND": "character_trajectory",
    "SCENE_YEARNING_ABSENT": "character_trajectory",
    "SDT_REGULATION_DRIFT": "character_trajectory",
    "SIGNED_GRAPH_OVERLY_COZY": "character_trajectory",
    "SIGNED_GRAPH_OVERLY_HOSTILE": "character_trajectory",
    "STAGE_JUMP": "character_trajectory",
    "STAGE_NOT_UPDATED": "character_trajectory",
    "STAGE_REGRESS": "character_trajectory",
    "STAGE_STAGNATION": "character_trajectory",
    "STRATEGIC_EMPATHY_MISALIGNED": "character_trajectory",
    "STRESS_PERMA_HIGH_NO_BREAK": "character_trajectory",
    "STRESS_RUNAWAY": "character_trajectory",
    "UNKNOWN_CHARACTER_DETECTED": "character_trajectory",
    "YEARNING_LAYER_MONOTONE": "character_trajectory",
    # ---- action_mentalizing（动作/内省比例） ----
    "BODY_REACTION_OVERUSE": "action_mentalizing",
    "INTERIORITY_MODE_IMBALANCE": "action_mentalizing",
    "STAGING_BUCKET_UNBALANCED": "action_mentalizing",
    "STAGING_TALKING_HEADS": "action_mentalizing",
    "STAGING_THIN": "action_mentalizing",
    # ---- cognitive_load（认知负荷/读者负荷/角色数量经济） ----
    "CAST_COMPOSITE_HINT": "cognitive_load",
    "CAST_INTRODUCE_BURST": "cognitive_load",
    "CAST_ROLE_SPLIT_IMPLICIT": "cognitive_load",
    "EXPERT_BLINDSPOT_OK": "cognitive_load",
    "PRESENCE_GINI_DEVIATION": "cognitive_load",
    "PRESENCE_LONG_TAIL_FORGOTTEN": "cognitive_load",
    # ---- judge_reliability（judge/arbiter 机制可靠性，非正文判断——沿用 _collect_judge_reports 既有池名） ----
    "ADVERSARIAL_JUDGE_DEGRADED": "judge_reliability",
    "JUDGE_SCORE_DECLINE": "judge_reliability",
    "JUDGE_SCORE_PLATEAU": "judge_reliability",
    "JUDGE_SCORE_VOLATILITY": "judge_reliability",
    "PREV_FINDINGS_IGNORED": "judge_reliability",
    # ---- waiver_calibration（豁免行为校准——沿用 _collect_audit_metadata 既有池名） ----
    "WAIVER_PERSISTENT_CODE": "waiver_calibration",
    "WAIVER_RUNAWAY": "waiver_calibration",
    # ---- scanner_reliability（脚本/工具自身运行可靠性，非正文判断——沿用既有池名） ----
    "AFFECTIVE_THEME_ITERATION_DEGRADED": "scanner_reliability",
    "DIALOGUE_ORCHESTRATOR_DEGRADED": "scanner_reliability",
    "PLAN_SCRIPT_MISSING": "scanner_reliability",
    "SUMMARY_FIRST_QUARTER_OVERWEIGHT": "scanner_reliability",
    "SUMMARY_KEYWORD_MISMATCH": "scanner_reliability",
    "SUMMARY_TAIL_BIAS": "scanner_reliability",
    "SUMMARY_TOO_SHORT": "scanner_reliability",
    "VALIDATE_CLUSTER_EXCEPTION": "scanner_reliability",
    # ---- reader_experience（读者体验代理指标——沿用 READING_DIMENSION_TO_MODEL 既有池名） ----
    "IMPLIED_AUTHOR_NARRATEE_THIN": "reader_experience",
    "IMPLIED_AUTHOR_SCREEN_ASYMMETRY": "reader_experience",
    "IMPLIED_AUTHOR_TELLING_THIN": "reader_experience",
    "PARAGRAPH_ENGAGEMENT_FLATLINE": "reader_experience",
    "RETENTION_PROXY_LOW": "reader_experience",
}


# audit_hub.py / biber_mda_scanner.py 等少数 code 是运行时 f-string 动态拼接（人名/维度名
# 后缀），静态表锁不住后缀变量，精确匹配前用前缀兜底。宁缺勿滥——只登记「后缀无论是什么
# 语义桶都不变」的干净前缀族，语义会随后缀变化的（如 audit_hub 的 STYLE_{name}/
# {scanner}_{check} 那批混装多个维度的动态族）不注册前缀，留作已知的动态未覆盖范围。
CODE_PREFIX_TO_MODEL: dict[str, str] = {
    # audit_hub._check_character_arc_drift: f"CHARACTER_ARC_DRIFT_{safe_name.upper()}"
    "CHARACTER_ARC_DRIFT_": "character_trajectory",
    # biber_mda_scanner.py: f"{ISSUE_CODE}_{dim}"（dim=D1-D4·scanner_registry.json 已确认）
    "BIBER_MDA_DRIFT_": "style_fidelity",
}


# 显式豁免：静态扫描到、但刻意不收进训练池的 code（连同理由，供人工审查 + 回归测试核对）。
# 全部是「非正文创作判断」信号（ledger 记账/文件契约/蒸馏管线自检/系统自诊断/自学习闭环元信号/
# 窄众题材暂缓），不是遗漏——归桶宁保守勿强塞，语义不贴合的宁可放这里也不硬塞 13 桶。
EXCLUDED_FROM_FLYWHEEL: dict[str, str] = {
    # 文件/流水线契约核对（客观存在性检查·非创作判断，同 validate_chapter.py 既有 hard_gate 契约族）
    "CHANGES_MISSING": "文件/流水线契约核对（客观存在性检查·非创作判断，同 validate_chapter.py 既有 hard_gate 契约族）",
    "FILE_NOT_FOUND": "文件/流水线契约核对（客观存在性检查·非创作判断，同 validate_chapter.py 既有 hard_gate 契约族）",
    "MANIFEST_MISSING": "文件/流水线契约核对（客观存在性检查·非创作判断，同 validate_chapter.py 既有 hard_gate 契约族）",
    "USER_CHOICE_CLUSTER_ID_MISMATCH": "文件/流水线契约核对（客观存在性检查·非创作判断，同 validate_chapter.py 既有 hard_gate 契约族）",
    "USER_CHOICE_LANDED_MISMATCH": "文件/流水线契约核对（客观存在性检查·非创作判断，同 validate_chapter.py 既有 hard_gate 契约族）",
    # 一致性硬核对（锁定事实/物件持有客观冲突·非主观工艺判断，性质同 hard_gate 契约）
    "ITEM_HOLDER_ABSENT": "一致性硬核对（锁定事实/物件持有客观冲突·非主观工艺判断，性质同 hard_gate 契约）",
    "ITEM_NOT_YET_INTRODUCED": "一致性硬核对（锁定事实/物件持有客观冲突·非主观工艺判断，性质同 hard_gate 契约）",
    "LOCKED_FACT_CONFLICT": "一致性硬核对（锁定事实/物件持有客观冲突·非主观工艺判断，性质同 hard_gate 契约）",
    "LOCKED_FACT_CROSS_SCENE_CONFLICT": "一致性硬核对（锁定事实/物件持有客观冲突·非主观工艺判断，性质同 hard_gate 契约）",
    # 导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）
    "CHAPTER_BODY_FILE_MISSING": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "CHAPTER_DUPLICATE": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "CHAPTER_READ_OR_CONTRACT_ERROR": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "CHAPTER_SOURCE_MISSING": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "PENDING_TAIL_PRESENT": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "PENDING_TAIL_SILENT_LOSS_OVER_THRESHOLD": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "CHAPTER_MISSING": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "CHAPTER_OUT_OF_ORDER": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "CLUSTER_RANGE_UNCOVERED": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "SPLIT_WORD_NOT_CONSERVED": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    "WORD_CONSERVATION_DRIFT": "导出/切章格式契约（纯格式层字数守恒核对·非创作判断，北极星④章节仅格式边界）",
    # cluster 长度带遥测（LongWriter 长输出长度体检·下游 advisory 遥测非可学习正文质量信号·
    # 北极星⑤字数自然涌现是 v27 纯 freestyle 已定调，长度带外≠文本工艺差，混入会稀释训练池质量）
    "CLUSTER_LENGTH_UNDER_BAND": "cluster 长度带遥测（LongWriter 长输出长度体检·下游 advisory 遥测非可学习正文质量信号·北极星⑤字数自然涌现，长度带外≠文本工艺差）",
    "CLUSTER_LENGTH_OVER_BAND": "cluster 长度带遥测（LongWriter 长输出长度体检·下游 advisory 遥测非可学习正文质量信号·北极星⑤字数自然涌现，长度带外≠文本工艺差）",
    # 蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）
    "BANNED_PHRASES_MALFORMED": "蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）",
    "HOLDOUT_SFS_GAP_OVERFIT": "蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）",
    "INSUFFICIENT_PROVENANCE": "蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）",
    "SAME_STACK_PROVENANCE_MISSING": "蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）",
    "VOICE_PACK_MISSING": "蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）",
    "VOICE_SAMPLES_MISSING": "蒸馏管线自身校验（验证蒸馏产物结构完整性·不评判正文文本本身）",
    # 世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）
    "ASPECT_NOT_ADDRESSED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "DEBT_BOOK_MORTGAGE_ABSENT": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "DEBT_VOLUME_OVERSHOOT": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "DEBT_VOLUME_TAIL_RUNAWAY": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "EVENTS_PARTIAL_TRIGGERED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "EVENT_OVERDUE": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "FACTION_NEAR_MAX": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "FACTION_NEAR_ZERO": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "FACTION_STANDINGS_FROZEN": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "FATE_DICE_EVIDENCE_LOW": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "FATE_DICE_NOT_DECLARED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "FATE_EVENT_OVERDUE": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "HEART_EVENT_FORGOTTEN": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "ITEM_ABANDONED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "ITEM_DUPLICATE_HOLDER": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "RELATIONSHIPS_STAGNANT": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "RIPPLE_ABUSED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "RIPPLE_DEAD": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "SECRET_OVERDUE": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "STORYTELLER_TARGET_LIKELY_TO_BE_IGNORED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "TIME_FROZEN": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "TIME_GAP_UNEXPLAINED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "TRAVEL_LOG_BARREN": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "TRIGGERED_EVENTS_EMPTY": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "URGENT_CLOCK_IGNORED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    "WILL_LEARN_NOT_TRIGGERED": "世界状态/数值账本记账（JSON 状态字段核对·text 取的是结构化描述非可分类正文，混入会稀释训练池质量）",
    # 自学习闭环元信号（学的是系统自身报错/经验复用模式·非单 cluster 正文质量，见 SELF_LEARNING_ARCHITECTURE.md MAPE-K 层）
    "FAILURE_RECURRING": "自学习闭环元信号（学的是系统自身报错/经验复用模式·非单 cluster 正文质量，见 SELF_LEARNING_ARCHITECTURE.md MAPE-K 层）",
    "SUCCESS_NEVER_REUSED": "自学习闭环元信号（学的是系统自身报错/经验复用模式·非单 cluster 正文质量，见 SELF_LEARNING_ARCHITECTURE.md MAPE-K 层）",
    "WRITER_GROWTH_NO_RESPONSE_TO_FEEDBACK": "自学习闭环元信号（学的是系统自身报错/经验复用模式·非单 cluster 正文质量，见 SELF_LEARNING_ARCHITECTURE.md MAPE-K 层）",
    "WRITER_GROWTH_VOCAB_DROP": "自学习闭环元信号（学的是系统自身报错/经验复用模式·非单 cluster 正文质量，见 SELF_LEARNING_ARCHITECTURE.md MAPE-K 层）",
    # 窄众题材/暂缓（拆字体裁高度受限·样本稀疏不足以支撑训练，团队先验已明确标记暂缓）
    "CHAIZI_DENSITY_THIN": "窄众题材/暂缓（拆字体裁高度受限·样本稀疏不足以支撑训练，团队先验已明确标记暂缓）",
    "CHAIZI_INCONSISTENT": "窄众题材/暂缓（拆字体裁高度受限·样本稀疏不足以支撑训练，团队先验已明确标记暂缓）",
    # 标签词典维护工具（校验 trope 标签词典本身完整性·非正文判断）
    "TROPE_CANON_DICT_THIN": "标签词典维护工具（校验 trope 标签词典本身完整性·非正文判断）",
    "TROPE_NEW_SURFACE_PROMOTION_CANDIDATE": "标签词典维护工具（校验 trope 标签词典本身完整性·非正文判断）",
    # 系统自诊断（涌现候选生成机制自检·非正文判断）
    "SANDBOX_EMERGENCE_ABNORMAL": "系统自诊断（涌现候选生成机制自检·非正文判断）",
}


def resolve_model_for_code(code: str | None) -> str | None:
    """统一 code→训练桶查表：大小写不敏感 + 精确优先 + 前缀兜底。

    大小写不敏感是根治性修复：audit_hub._parse_scanner_json 用
    f"{scanner.upper()}_{check}" 拼 code 时只大写了 scanner 前缀（如 scanner="semantic"）、
    没有 `.upper()` check 部分（check 取自 SEMANTIC_DIM 的小写 key，如 "metaphor_explain"），
    实际 emit 的是 "SEMANTIC_metaphor_explain"（混合大小写），但 CODE_TO_MODEL 里注册的是
    全大写 "SEMANTIC_METAPHOR_EXPLAIN"——原先 _collect_weak_labels 直接 `.get(code)`
    大小写敏感查表，8 个已注册的 SEMANTIC_* code 从未真正命中过，训练信号静默丢失。
    这里统一 `.upper()` 归一化后再查表，一次性治好这整类大小写漂移。

    调用方（_collect_weak_labels / _collect_strong_labels / _brief_model）统一走此函数，
    不再各自直接 `CODE_TO_MODEL.get(code)`。
    """
    if not code:
        return None
    norm = code.strip().upper()
    if not norm:
        return None
    if norm in CODE_TO_MODEL:
        return CODE_TO_MODEL[norm]
    for prefix, model in CODE_PREFIX_TO_MODEL.items():
        if norm.startswith(prefix):
            return model
    return None

